INSERT INTO languages (language, country) VALUES 
('English', 'United States'),
('Azərbaycan dili', 'Azərbaycan'),
('Bahasa Indonesia', 'Indonesia'),
('Bosanski', 'Bosna i Hercegovina'),
('Català', 'Espanya'),
('Čeština', 'Česká republika'),
('Crnogorski', 'Crna Gora'),
('Dansk', 'Danmark'),
('Deutsch', 'Deutschland'),
('Deutsch', 'Österreich'),
('Deutsch', 'Schweiz'),
('Eesti', 'Eesti'),
('English', 'Australia'),
('English', 'Canada'),
('English', 'Guyana'),
('English', 'India'),
('English', 'Ireland'),
('English', 'New Zealand'),
('English', 'Singapore'),
('English', 'United Arab Emirates'),
('English', 'United Kingdom'),
('Español', 'Argentina'),
('Español', 'Belice'),
('Español', 'Bolivia'),
('Español', 'Chile'),
('Español', 'Columbia'),
('Español', 'Costa Rica'),
('Español', 'Ecuador'),
('Español', 'El Salvador'),
('Español', 'España'),
('Español', 'Estados Unidos'),
('Español', 'Guatemala'),
('Español', 'Honduras'),
('Español', 'Latinoamérica'),
('Español', 'México'),
('Español', 'Nicaragua'),
('Español', 'Panamá'),
('Español', 'Paraguay'),
('Español', 'Perú'),
('Español', 'Venezuela'),
('Français', 'Belgique'),
('Français', 'Canada'),
('Français', 'France'),
('Français', 'Suisse'),
('Gaeilge', 'Éire'),
('Hrvatski', 'Hrvatska'),
('isiXhosa', 'eMzantsi Afrika'),
('isiZulu', 'iNingizimu Afrika'),
('Islenska', 'Island'),
('Italiano', 'Italia'),
('Italiano', 'Svizzera'),
('Kiswahili', 'Afrika'),
('Latviesu', 'Latvija'),
('Lietuviu', 'Lietuva'),
('Magyar', 'Magyarorszag'),
('Malti', 'Malta'),
('Melayu', 'Malaysia'),
('Netherlands', 'Belgie'),
('Netherlands', 'Netherland'),
('Norsk', 'Norge'),
('Polski', 'Polska'),
('Portugues', 'Brazil'),
('Portugues', 'Portugal'),
('Romana', 'Romania'),
('Shqip', 'Shqiperi'),
('Slovencina', 'Slovensko'),
('Srpski', 'Srbija'),
('Suomi', 'Suomi'),
('Svenska', 'Sverige'),
('Tagalog', 'Pilipinas'),
('Tieng Viet', 'Việt Nam'),
('Turkce', 'Turkiye'),
('Ελληνικά', 'Ελλάδα');



INSERT INTO currencies (currency, symbol) VALUES 
('United States dollar', 'USD - $'),
('Australian dollar', 'AUD - $'),
('Brazilian real', 'BRL - R$'),
('Bulgarian lev', 'BGN - лв.'),
('Canadian Dollar', 'CAD - $'),
('Chilean peso', 'CLP - $'),
('Chinese yuan', 'CNY - ￥'),
('Coloumbian peso', 'COP - $'),
('Costa Rucan colon', 'CRC - ₡'),
('Croatian kuna', 'HRK - kn'),
('Czech koruna', 'CZK - '),
('Danish krone', 'DKK - kr'),
('Emirati dirham', 'AED - '),
('Euro', 'EUR - €'),
('Hong Kong dollar', 'HKD - $'),
('Hungarian forint', 'HUF - Ft'),
('Indian rupee', 'INR - ₹'),
('Israeli new shekel', 'ILS - ₪'),
('Japanese yen', 'JPY - ¥'),
('Malaysian ringgit', 'MYR - RM'),
('Mexican peso', 'MXN - $'),
('Moroccan dirham', 'MAD'),
('New Taiwan dollar', 'TWD - $'),
('New Zealand dollar', 'NZD - $'),
('Norwegian krone', 'NOK - kr'),
('Peruvian sol', 'PEN - S/'),
('Philippine peso', 'PHP - ₱'),
('Polish zloty', 'PLN - zł'),
('Pound sterling', 'GBP - £'),
('Romanian leu', 'RON - leu'),
('Saudi Arabian riyal', 'SAR - SR'),
('Singapore odllar', 'SGD - $'),
('South African rand', 'ZAR- R'),
('South Korean won', 'KRW - ₩'),
('Swedish krona', 'SEK - kr'),
('Swiss franc', 'CHF'),
('Thai baht', 'THB - ฿'),
('Turkish lira', 'TRY - ₺'),
('Uruguayan peso', 'UYU - $U');